services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: systemslabs
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  lb:
    image: nginx:alpine
    restart: always
    ports:
      - '4000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db-data:
