events {
    worker_connections 1024;
}

http {
    upstream backend_cluster {
        # Emulating an Auto Scaling Group with 4 instances
        server host.docker.internal:3000;
        server host.docker.internal:3001;
        server host.docker.internal:3002;
        server host.docker.internal:3003;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_cluster;
            
            # WebSocket Support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            # Forward real IP and Host
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # The Load Tester SSE Endpoint should bypass buffering
        location /api/engine/stream {
            proxy_pass http://backend_cluster;
            proxy_set_header Connection '';
            proxy_http_version 1.1;
            chunked_transfer_encoding off;
            proxy_buffering off;
            proxy_cache off;
        }
    }
}
